common:
    image_left_topic: "/cam0/image_raw"
    image_right_topic: "/cam1/image_raw"
    imu_topic: "/imu0"
    
state_parameter:
    use_fej: true                        # if first-estimate Jacobians should be used (enable for good consistency)
    calib_cam_extrinsics: false          # if the transform between camera and IMU should be optimized R_ItoC, p_CinI
    calib_cam_intrinsics: false          # if camera intrinsics should be optimized (focal, center, distortion)
    calib_cam_timeoffset: false          # if timeoffset between camera and IMU should be optimized
    calib_imu_intrinsics: false          # if imu intrinsics should be calibrated (rotation and skew-scale matrix)
    calib_imu_g_sensitivity: false       # if gyroscope gravity sensitivity (Tg) should be calibrated
    imu_intrinsics_model: "kalibr"       # "calibrated" (same as "kalibr"), "kalibr", "rpng"
    max_clones: 11                       # how many clones in the sliding window raw: 11
    max_slam: 100                        # number of features in our state vector raw: 50 200
    max_slam_in_update: 100              # update can be split into sequential updates of batches, how many in a batch raw: 25 200
    max_msckf_in_update: 100             # how many MSCKF features to use in the update raw: 40 200
    
initializer_parameter:
    init_window_time: 1.5                # how many seconds to collect initialization information 10.0 for MH_01, MH_02, MH_04, 2.0 for others
    init_imu_thresh: 0.45                 # threshold for variance of the accelerometer to detect a "jerk" in motion
    init_max_disparity: 15.0             # max disparity to consider the platform stationary (dependent on resolution)
    init_max_features: 50                # how many features to track during initialization (saves on computation)
    init_dyn_use: true                   # if dynamic initialization should be used
    init_dyn_mle_opt_calib: false        # if we should optimize calibration during intialization (not recommended)
    init_dyn_mle_max_iter: 50            # how many iterations the MLE refinement should use (zero to skip the MLE)
    init_dyn_mle_max_time: 0.05          # how many seconds the MLE should be completed in
    init_dyn_mle_max_threads: 6          # how many threads the MLE should use
    init_dyn_num_pose: 6                 # number of poses to use within our window time (evenly spaced)
    init_dyn_min_deg: 10.0               # orientation change needed to try to init
    init_dyn_inflation_ori: 10           # what to inflate the recovered q_GtoI covariance by
    init_dyn_inflation_vel: 100          # what to inflate the recovered v_IinG covariance by
    init_dyn_inflation_bg: 10            # what to inflate the recovered bias_g covariance by
    init_dyn_inflation_ba: 100           # what to inflate the recovered bias_a covariance by
    init_dyn_min_rec_cond: 1e-20         # reciprocal condition number thresh for info inversion
    init_dyn_bias_g: [ 0.0, 0.0, 0.0 ]   # initial gyroscope bias guess
    init_dyn_bias_a: [ 0.0, 0.0, 0.0 ]   # initial accelerometer bias guess
    gravity_mag: 9.80766                 # magnitude of gravity in this location
    downsample_cameras: false               # will downsample image in half if true

imu_parameter:
    accelerometer_noise_density: 0.0028     # [m/s^2/sqrt(Hz)]   ( accel "white noise" )
    accelerometer_random_walk: 0.00086      # [m/s^3/sqrt(Hz)]   ( accel bias diffusion )
    gyroscope_noise_density: 0.00016        # [rad/s/sqrt(Hz)]   ( gyro "white noise" )
    gyroscope_random_walk: 2.2e-05          # [rad/s^2/sqrt(Hz)] ( gyro bias diffusion )
    sigma_pix: 1.0
    Tw: [ 1.0, 0.0, 0.0, 
          0.0, 1.0, 0.0, 
          0.0, 0.0, 1.0 ]
    Ta: [ 1.0, 0.0, 0.0, 
          0.0, 1.0, 0.0, 
          0.0, 0.0, 1.0 ]
    R_acc_imu: [ 1.0, 0.0, 0.0, 
                 0.0, 1.0, 0.0, 
                 0.0, 0.0, 1.0 ]
    R_gyr_imu: [ 1.0, 0.0, 0.0, 
                 0.0, 1.0, 0.0, 
                 0.0, 0.0, 1.0 ]
    Tg: [ 0.0, 0.0, 0.0, 
          0.0, 0.0, 0.0, 
          0.0, 0.0, 0.0 ]
    
camera_parameter:
    timeshift_cam_imu_left: 0.0
    timeshift_cam_imu_right: 0.0
    distortion_model_left: equidistant
    distortion_model_right: equidistant
    intrinsics_left: [190.978477, 190.973307, 254.931706, 256.897442]   # fx, fy, cx, cy
    intrinsics_right: [190.442369, 190.434438, 252.599497, 254.917230]   # fx, fy, cx, cy
    distortion_coeffs_left: [0.00348239, 0.000715035, -0.00205324, 0.000202937]
    distortion_coeffs_right: [0.00340032, 0.00176628, -0.00266313, 0.000329952]
    resolution_left: [512, 512]
    resolution_right: [512, 512]
    T_imu_cam_left: [-0.999525, 0.00750192, -0.0298901, 0.0455748, 
                     0.0296153, -0.0343974, -0.998969, -0.0711618, 
                     -0.00852233, -0.99938, 0.0341589, -0.0446813, 
                     0.0, 0.0, 0.0, 1.0]
    T_imu_cam_right: [-0.999511, 0.00810408, -0.0301991, -0.0554563, 
                      0.0302991, 0.0125116, -0.999463, -0.06925, 
                      -0.00772188, -0.999889, -0.0127511, -0.0474529, 
                      0.0, 0.0, 0.0, 1.0]
    mask_left_path: "/home/yuanzikang/Projects/Voxel-SVIO/src/voxel_svio/config/mask_tumvi0.png"
    mask_right_path: "/home/yuanzikang/Projects/Voxel-SVIO/src/voxel_svio/config/mask_tumvi1.png"
                      
odometry_parameter:
    use_mask: true
    use_huber: true
    use_keyframe: true
    dt_slam_delay: 2
    up_msckf_sigma_px: 1
    up_msckf_chi2_multipler: 1
    up_slam_sigma_px: 1
    up_slam_chi2_multipler: 1
    downsample_cameras: false
    num_pts: 1000  # raw: 200 1000
    fast_threshold: 20
    patch_size_x: 5
    patch_size_y: 5
    min_px_dist: 10
    histogram_method: "histogram"
    track_frequency: 21.0
    
feature_parameter:
    refine_features: true
    max_runs: 5
    init_lamda: 1e-3
    max_lamda: 1e10
    min_dx: 1e-6
    min_dcost: 1e-6
    lam_mult: 10.0
    min_dist: 0.10
    max_dist: 60.0
    max_baseline: 40.0
    max_cond_number: 10000.0
    keyframe_parallax: 20

voxel_parameter:
    voxel_size: 0.3             # raw: 0.1
    use_all_points: false
    max_num_points_in_voxel: 5
    min_distance_points: 0.0    # raw: 0.03
    nb_voxels_visited: 2
